version: '3.8'

services:
  # Frontend (React PWA)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_ENABLE_PWA=true
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
    command: npm run dev

  # Backend (Node.js API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - COUCHDB_URL=http://couchdb:5984
    depends_on:
      - couchdb
    volumes:
      - ./server:/app
      - uploads:/app/uploads
    command: npm run dev

  # CouchDB for sync
  couchdb:
    image: couchdb:3.3
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_config:/opt/couchdb/etc/local.d
    restart: unless-stopped

  # Nginx for production (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    profiles:
      - production

volumes:
  couchdb_data:
  couchdb_config:
  uploads:

networks:
  default:
    driver: bridge